FROM  registry.access.redhat.com/ubi9/python-311

#RUN mkdir /opt
COPY requirements.txt /opt/requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /opt/requirements.txt
#RUN pip install --no-cache-dir --upgrade --target vendor -r /opt/requirements.txt
EXPOSE 8083

ENTRYPOINT ["cps"]
